In [51]:
for i in range(5):
    a=5
    b=10
    c=a+b
print(c)

15


In [25]:
x=[0,1]
for i in range(0,50):
    x+= [(x[i] + x[i+1])]
print(x)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074]


In [50]:
def greatest(a,b,c):
    if(a>b and a>c):
        great= a
    if(b>a and b>c):
        great= b
    else:
        great= c
    return(great)
a= 5
b=6
c=9
g= greatest(a,b,c)
print(g)

9


In [30]:
import numpy as np
a= np.array([[1,2], [4,5]])
b= np.array([[8,9], [7,4]])
c= np.dot(a,b)
d= np.cross(a,b)
print(c,d)

[[22 17]
 [67 56]] [ -7 -19]


In [40]:
import random
a= np.random.randint(1,9, (2,2))
b= np.random.randint(1,9, (2,2))
abdot= np.dot(a, b)
abcross= np.cross(a, b)
abadd= np.add(a,b)
print(a)
print(b)
print("dot prod\n", abdot)
print("cross product\n", abcross)
print("add\n", abadd)

[[1 6]
 [8 5]]
[[8 5]
 [7 2]]
dot prod
 [[50 17]
 [99 50]]
cross product
 [-43 -19]
add
 [[ 9 11]
 [15  7]]


In [46]:
import pandas as pd
df= pd.read_csv("/home/ibab/Downloads/pima-indians-diabetes-database/diabetes.csv", header= None)
df.head()

0        1              2              3        4     5  \
0  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI   
1            6      148             72             35        0  33.6   
2            1       85             66             29        0  26.6   
3            8      183            NaN              0        0  23.3   
4            1       89             66             23       94  28.1   

                          6    7        8  
0  DiabetesPedigreeFunction  Age  Outcome  
1                     0.627   50        1  
2                     0.351   31      NaN  
3                     0.672   32        1  
4                     0.167   21      NaN

In [47]:
df.isnull()

0      1      2      3      4      5      6      7      8
0    False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False   True
3    False  False   True  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False   True
5    False  False  False  False  False  False  False  False  False
6    False  False  False   True  False  False  False  False  False
7    False  False  False  False  False  False  False  False  False
8    False  False  False  False  False  False  False  False  False
9    False  False  False  False  False   True  False  False  False
10   False  False  False  False  False  False  False  False  False
11   False  False  False  False   True  False   True  False  False
12   False  False  False  False  False  False  False  False  False
13   False   True  False  False  False  False  False  False  False
14   False  False  False  False  False   True  False  False  False
15   False  False  False  False  False  False  False  False  False
16   False  False  False  False  False  False  False  False  False
17   False  False  False  False  False  False  False  False  False
18   False  False  False  False  False  False  False  False  False
19   False  False  False  False  False  False  False  False  False
20   False  False  False  False  False  False  False  False  False
21   False  False  False  False  False  False  False  False   True
22   False  False  False  False  False  False  False  False  False
23   False  False  False  False  False  False  False  False   True
24   False  False  False  False  False  False  False  False  False
25   False  False  False  False  False  False  False  False  False
26   False  False  False  False  False  False  False  False  False
27   False  False  False  False  False  False  False  False  False
28   False  False  False  False  False  False  False  False  False
29   False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...
739  False  False  False  False  False  False  False  False  False
740  False  False  False  False  False  False  False  False  False
741  False  False  False  False  False  False  False  False  False
742  False  False  False  False  False  False  False  False  False
743  False  False  False  False  False  False  False  False  False
744  False  False  False  False  False  False  False  False  False
745  False  False  False  False  False  False  False  False  False
746  False  False  False  False  False  False  False  False  False
747  False  False  False  False  False  False  False  False  False
748  False  False  False  False  False  False  False  False  False
749  False  False  False  False  False  False  False  False  False
750  False  False  False  False  False  False  False  False  False
751  False  False  False  False  False  False  False  False  False
752  False  False  False  False  False  False  False  False  False
753  False  False  False  False  False  False  False  False  False
754  False  False  False  False  False  False  False  False  False
755  False  False  False  False  False  False  False  False  False
756  False  False  False  False  False  False  False  False  False
757  False  False  False  False  False  False  False  False  False
758  False  False  False  False  False  False  False  False  False
759  False  False  False  False  False  False  False  False  False
760  False  False  False  False  False  False  False  False  False
761  False  False  False  False  False  False  False  False  False
762  False  False  False  False  False  False  False  False  False
763  False  False  False  False  False  False  False  False  False
764  False  False  False  False  False  False  False  False  False
765  False  False  False  False  False  False  False  False  False
766  False  False  False  False  False  False  False  Fa

In [48]:
newdf= df.fillna(0)
newdf.head()

0        1              2              3        4     5  \
0  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI   
1            6      148             72             35        0  33.6   
2            1       85             66             29        0  26.6   
3            8      183              0              0        0  23.3   
4            1       89             66             23       94  28.1   

                          6    7        8  
0  DiabetesPedigreeFunction  Age  Outcome  
1                     0.627   50        1  
2                     0.351   31        0  
3                     0.672   32        1  
4                     0.167   21        0

In [49]:
newdf.iloc[:3]

0        1              2              3        4     5  \
0  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI   
1            6      148             72             35        0  33.6   
2            1       85             66             29        0  26.6   

                          6    7        8  
0  DiabetesPedigreeFunction  Age  Outcome  
1                     0.627   50        1  
2                     0.351   31        0